import React, { useState, useEffect } from 'react';
import { TaxSummary } from '../types';
import { calculateTaxLiability, formatCurrency, formatPercent } from '../utils';
import { DIVIDEND_EXEMPTION_LIMIT_2025, TAX_BRACKETS_2025 } from '../constants';
import { FileText, Printer, CheckSquare, AlertCircle, Edit3, RefreshCw, User, Building, Calculator, BookOpen, ArrowRight, Sigma, Layers } from 'lucide-react';

interface DeclarationHelperProps {
  summary: TaxSummary;
  onNavigateToGuide?: () => void;
}

export const DeclarationHelper: React.FC<DeclarationHelperProps> = ({ summary, onNavigateToGuide }) => {
  const [mode, setMode] = useState<'auto' | 'manual'>('auto');
  
  // Form State
  const [name, setName] = useState('');
  const [tcNo, setTcNo] = useState('');
  const [taxOffice, setTaxOffice] = useState('');
  
  // Manual Calculation State
  const [manualTradingProfit, setManualTradingProfit] = useState<number>(0);
  const [manualDividendGross, setManualDividendGross] = useState<number>(0);
  const [manualWithholding, setManualWithholding] = useState<number>(0);

  // Derived Values (Active)
  const activeTradingProfit = mode === 'auto' ? summary.totalCapitalGainsProfitTry : manualTradingProfit;
  const activeDividendGross = mode === 'auto' ? summary.totalDividendProfitTry : manualDividendGross;
  const activeWithholding = mode === 'auto' ? (summary.foreignTaxCreditTry > 0 ? summary.foreignTaxCreditTry : 0) : manualWithholding; // Note: In auto summary, credit might be capped. We approximate here.

  // Real-time Calc Logic for Declaration View
  const isDividendExempt = activeDividendGross <= DIVIDEND_EXEMPTION_LIMIT_2025;
  const declaredDividend = isDividendExempt ? 0 : activeDividendGross;
  
  // "Değer Artış Kazancı" is typically net of indexed cost
  const taxableTrading = Math.max(0, activeTradingProfit);
  
  const totalTaxableIncome = taxableTrading + declaredDividend;
  
  const { tax: calculatedTax } = calculateTaxLiability(totalTaxableIncome);
  
  // Foreign tax credit logic (Capped at the tax amount attributable to foreign income, simplified here as total tax cap)
  // In Turkey, you can deduct foreign tax up to the amount of tax generated by that income in Turkey.
  const deductibleForeignTax = Math.min(activeWithholding, calculatedTax);
  
  const finalTaxPayable = Math.max(0, calculatedTax - deductibleForeignTax);
  const stampDuty = 586.80; // 2025 Estimated Damga Vergisi (Hypothetical)

  useEffect(() => {
    // Initialize manual values from auto summary on mount to make editing easier
    if (mode === 'manual' && manualTradingProfit === 0) {
      setManualTradingProfit(summary.totalCapitalGainsProfitTry);
      setManualDividendGross(summary.totalDividendProfitTry);
      // We don't have raw withholding total in summary easily accessible without recalc, 
      // but foreignTaxCreditTry is usually the claimed amount. 
      setManualWithholding(summary.foreignTaxCreditTry); 
    }
  }, [mode, summary]);

  const handlePrint = () => {
    window.print();
  };

  // --- PROGRESSIVE TAX LOGIC VISUALIZATION HELPER ---
  const getTaxBreakdown = () => {
    const breakdown = [];
    let remainingIncome = totalTaxableIncome;
    
    for (let i = 0; i < TAX_BRACKETS_2025.length; i++) {
      const bracket = TAX_BRACKETS_2025[i];
      const prevLimit = i === 0 ? 0 : TAX_BRACKETS_2025[i-1].limit;
      const width = bracket.limit - prevLimit;
      
      if (remainingIncome <= 0) break;

      // If bracket limit is Infinity, take all remaining
      const taxableInThisBracket = (bracket.limit === Infinity) 
        ? remainingIncome 
        : Math.min(remainingIncome, width);

      const taxForThisBracket = taxableInThisBracket * bracket.rate;

      breakdown.push({
        rate: bracket.rate,
        base: taxableInThisBracket,
        tax: taxForThisBracket,
        rangeLabel: i === 0 
          ? `0 - ${formatCurrency(bracket.limit, 'TRY', 0)}` 
          : bracket.limit === Infinity 
            ? `${formatCurrency(prevLimit, 'TRY', 0)} üzeri`
            : `${formatCurrency(prevLimit, 'TRY', 0)} - ${formatCurrency(bracket.limit, 'TRY', 0)}`
      });

      remainingIncome -= taxableInThisBracket;
    }
    return breakdown;
  };

  const taxBreakdown = getTaxBreakdown();

  return (
    <div className="space-y-6 pb-12 max-w-5xl mx-auto">
      {/* Help Banner */}
      <div className="bg-gradient-to-r from-blue-50 to-indigo-50 p-4 rounded-xl border border-blue-100 flex flex-col sm:flex-row items-center justify-between gap-4 shadow-sm">
        <div className="flex items-center gap-3">
          <div className="bg-white p-2 rounded-full text-blue-600 shadow-sm border border-blue-100">
            <BookOpen size={20} />
          </div>
          <div>
            <h4 className="font-bold text-slate-800 text-sm">İlk defa mı beyanname dolduruyorsunuz?</h4>
            <p className="text-xs text-slate-500">Hazır Beyan Sistemi ekranlarında nereye ne yazacağınızı adım adım öğrenin.</p>
          </div>
        </div>
        <button 
          onClick={onNavigateToGuide}
          className="whitespace-nowrap flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium rounded-lg transition-colors shadow-sm"
        >
          Adım Adım Rehberi Aç <ArrowRight size={16} />
        </button>
      </div>

      {/* Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white p-6 rounded-xl shadow-sm border border-slate-200">
        <div>
          <h2 className="text-2xl font-bold text-slate-800 flex items-center gap-2">
            <FileText className="text-blue-600" />
            Yıllık Gelir Vergisi Beyanname Taslağı
          </h2>
          <p className="text-slate-500 text-sm mt-1">
            2025 Takvim Yılı Gelirleri İçin (Mart 2026'da Verilecek)
          </p>
        </div>
        <div className="flex gap-3">
          <div className="bg-slate-100 p-1 rounded-lg flex border border-slate-200">
            <button
              onClick={() => setMode('auto')}
              className={`px-3 py-1.5 text-sm font-medium rounded-md flex items-center gap-2 transition-all ${mode === 'auto' ? 'bg-white text-blue-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
            >
              <RefreshCw size={14} /> Otomatik (Portföy)
            </button>
            <button
              onClick={() => setMode('manual')}
              className={`px-3 py-1.5 text-sm font-medium rounded-md flex items-center gap-2 transition-all ${mode === 'manual' ? 'bg-white text-blue-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
            >
              <Edit3 size={14} /> Manuel Düzenle
            </button>
          </div>
          <button 
            onClick={handlePrint}
            className="px-4 py-2 bg-slate-800 text-white rounded-lg flex items-center gap-2 hover:bg-slate-700 transition-colors shadow-sm"
          >
            <Printer size={16} /> Yazdır / PDF
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column: Form Inputs & Checklist */}
        <div className="lg:col-span-1 space-y-6 print:hidden">
          
          {/* Personal Info */}
          <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-sm">
            <h3 className="font-bold text-slate-800 mb-4 flex items-center gap-2">
              <User size={18} className="text-slate-400" /> Mükellef Bilgileri
            </h3>
            <div className="space-y-3">
              <div>
                <label className="text-xs font-semibold text-slate-500 block mb-1">Ad Soyad</label>
                <input 
                  type="text" 
                  value={name} 
                  onChange={e => setName(e.target.value)} 
                  placeholder="Adınız Soyadınız"
                  className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-500 outline-none"
                />
              </div>
              <div>
                <label className="text-xs font-semibold text-slate-500 block mb-1">T.C. Kimlik No</label>
                <input 
                  type="text" 
                  value={tcNo} 
                  onChange={e => setTcNo(e.target.value)} 
                  placeholder="11 Haneli TCKN"
                  maxLength={11}
                  className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-500 outline-none"
                />
              </div>
              <div>
                <label className="text-xs font-semibold text-slate-500 block mb-1">Vergi Dairesi</label>
                <input 
                  type="text" 
                  value={taxOffice} 
                  onChange={e => setTaxOffice(e.target.value)} 
                  placeholder="İkametgah Vergi Dairesi"
                  className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-500 outline-none"
                />
              </div>
            </div>
          </div>

          {/* Manual Inputs (Only visible in Manual Mode) */}
          {mode === 'manual' && (
            <div className="bg-blue-50 p-5 rounded-xl border border-blue-100 shadow-sm animate-in fade-in slide-in-from-left-2">
              <h3 className="font-bold text-blue-800 mb-4 flex items-center gap-2">
                <Calculator size={18} /> Gelir Verileri (Manuel)
              </h3>
              <div className="space-y-3">
                <div>
                  <label className="text-xs font-semibold text-blue-700 block mb-1">Değer Artış Kazancı (Hisse Karı)</label>
                  <div className="relative">
                    <span className="absolute left-3 top-2 text-blue-400 font-bold">₺</span>
                    <input 
                      type="number" 
                      value={manualTradingProfit} 
                      onChange={e => setManualTradingProfit(Number(e.target.value))} 
                      className="w-full border border-blue-200 rounded-lg pl-8 pr-3 py-2 text-sm focus:ring-2 focus:ring-blue-500 outline-none"
                    />
                  </div>
                  <p className="text-sm text-blue-600 mt-1">Endeksleme sonrası net TL karı giriniz.</p>
                </div>
                <div>
                  <label className="text-xs font-semibold text-blue-700 block mb-1">Brüt Temettü Geliri</label>
                  <div className="relative">
                    <span className="absolute left-3 top-2 text-blue-400 font-bold">₺</span>
                    <input 
                      type="number" 
                      value={manualDividendGross} 
                      onChange={e => setManualDividendGross(Number(e.target.value))} 
                      className="w-full border border-blue-200 rounded-lg pl-8 pr-3 py-2 text-sm focus:ring-2 focus:ring-blue-500 outline-none"
                    />
                  </div>
                </div>
                <div>
                  <label className="text-xs font-semibold text-blue-700 block mb-1">Kesilen Yabancı Vergi (Stopaj)</label>
                  <div className="relative">
                    <span className="absolute left-3 top-2 text-blue-400 font-bold">₺</span>
                    <input 
                      type="number" 
                      value={manualWithholding} 
                      onChange={e => setManualWithholding(Number(e.target.value))} 
                      className="w-full border border-blue-200 rounded-lg pl-8 pr-3 py-2 text-sm focus:ring-2 focus:ring-blue-500 outline-none"
                    />
                  </div>
                  <p className="text-[10px] text-blue-600 mt-1">Sadece beyan edilen gelire ait stopajı giriniz.</p>
                </div>
              </div>
            </div>
          )}

          {/* Checklist */}
          <div className="bg-yellow-50 p-5 rounded-xl border border-yellow-100 shadow-sm">
            <h3 className="font-bold text-yellow-800 mb-4 flex items-center gap-2">
              <CheckSquare size={18} /> Hazırlık Kontrol Listesi
            </h3>
            <ul className="space-y-3 text-sm text-yellow-900">
              <li className="flex gap-2 items-start">
                <input type="checkbox" className="mt-1" />
                <span>Hazır Beyan Sistemi giriş şifreniz var mı? (E-Devlet ile girilebilir)</span>
              </li>
              <li className="flex gap-2 items-start">
                <input type="checkbox" className="mt-1" />
                <span>Banka / Aracı Kurum hesap dökümleriniz (Extre) PDF olarak hazır mı?</span>
              </li>
              <li className="flex gap-2 items-start">
                <input type="checkbox" className="mt-1" />
                <span>Yurt dışında ödenen vergilerin (Stopaj) mahsubu için, konsolosluk onaylı veya apostilli belge gerekeceğini biliyor musunuz? (Vergi dairesi bazen talep edebilir)</span>
              </li>
              <li className="flex gap-2 items-start">
                <input type="checkbox" className="mt-1" />
                <span>Hesaplamada kullanılan TCMB Döviz Alış kurlarının doğruluğunu teyit ettiniz mi?</span>
              </li>
            </ul>
          </div>
        </div>

        {/* Right Column: The "Formal" Declaration Preview */}
        <div className="lg:col-span-2 space-y-6">
          <div className="bg-white border-2 border-slate-300 p-8 rounded-none shadow-lg print:border-none print:shadow-none print:p-0">
            
            {/* Form Header */}
            <div className="text-center border-b-2 border-slate-800 pb-4 mb-6">
              <div className="flex justify-center mb-2">
                 <Building size={32} className="text-slate-800" />
              </div>
              <h1 className="text-xl font-bold text-slate-900 uppercase">Yıllık Gelir Vergisi Beyannamesi Özeti</h1>
              <p className="text-sm text-slate-600 font-semibold">(1001E - Hazır Beyan Sistemi İçin Veri Hazırlığı)</p>
            </div>

            {/* Section 1: Identity */}
            <div className="mb-6">
              <h4 className="bg-slate-100 text-slate-800 font-bold px-3 py-1 text-sm border border-slate-300 mb-2">1. MÜKELLEF BİLGİLERİ</h4>
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div className="border-b border-slate-200 pb-1">
                  <span className="text-slate-500 block text-xs">Adı Soyadı / Unvanı</span>
                  <span className="font-medium text-slate-900 min-h-[20px] block">{name || '...................................................'}</span>
                </div>
                <div className="border-b border-slate-200 pb-1">
                  <span className="text-slate-500 block text-xs">T.C. Kimlik No</span>
                  <span className="font-mono font-medium text-slate-900 min-h-[20px] block">{tcNo || '...........................'}</span>
                </div>
                <div className="border-b border-slate-200 pb-1 col-span-2">
                  <span className="text-slate-500 block text-xs">Vergi Dairesi</span>
                  <span className="font-medium text-slate-900 min-h-[20px] block">{taxOffice || '...................................................'}</span>
                </div>
              </div>
            </div>

            {/* Section 2: Income Details */}
            <div className="mb-6">
              <h4 className="bg-slate-100 text-slate-800 font-bold px-3 py-1 text-sm border border-slate-300 mb-2">2. GELİR BİLDİRİMİ</h4>
              
              <table className="w-full text-sm border-collapse">
                <thead>
                  <tr className="bg-slate-50 border-b border-slate-300">
                    <th className="text-left py-2 px-2 font-semibold text-slate-600">Gelir Türü</th>
                    <th className="text-right py-2 px-2 font-semibold text-slate-600">Brüt Tutar</th>
                    <th className="text-right py-2 px-2 font-semibold text-slate-600">İstisna/Gider</th>
                    <th className="text-right py-2 px-2 font-semibold text-slate-600">Safi İrat (Matrah)</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-200">
                  {/* Trading Row */}
                  <tr>
                    <td className="py-2 px-2">
                      <div className="font-medium">Diğer Kazanç ve İratlar</div>
                      <div className="text-xs text-slate-500 italic">Yurt Dışı Hisse Senedi Değer Artış Kazancı</div>
                    </td>
                    <td className="py-2 px-2 text-right font-mono text-slate-700">
                      {formatCurrency(taxableTrading)}
                    </td>
                    <td className="py-2 px-2 text-right font-mono text-slate-400">0,00 ₺</td>
                    <td className="py-2 px-2 text-right font-mono font-bold text-slate-800">
                      {formatCurrency(taxableTrading)}
                    </td>
                  </tr>

                  {/* Dividend Row */}
                  <tr>
                    <td className="py-2 px-2">
                      <div className="font-medium">Menkul Sermaye İradı</div>
                      <div className="text-xs text-slate-500 italic">Yurt Dışı Temettü Gelirleri</div>
                    </td>
                    <td className="py-2 px-2 text-right font-mono text-slate-700">
                      {formatCurrency(activeDividendGross)}
                    </td>
                    <td className="py-2 px-2 text-right text-xs">
                      {isDividendExempt ? (
                         <span className="text-green-600 bg-green-50 px-1 rounded">İstisna (Tamamı)</span>
                      ) : (
                         <span className="text-slate-400">Yok</span>
                      )}
                    </td>
                    <td className="py-2 px-2 text-right font-mono font-bold text-slate-800">
                      {formatCurrency(declaredDividend)}
                    </td>
                  </tr>
                </tbody>
                <tfoot>
                  <tr className="bg-slate-100 border-t-2 border-slate-300">
                    <td colSpan={3} className="py-2 px-2 text-right font-bold text-slate-800">TOPLAM GELİR MATRAHI:</td>
                    <td className="py-2 px-2 text-right font-bold text-slate-900 border-b-4 border-double border-slate-400">
                      {formatCurrency(totalTaxableIncome)}
                    </td>
                  </tr>
                </tfoot>
              </table>
            </div>

            {/* Section 3: Tax Calculation */}
            <div className="mb-8">
              <h4 className="bg-slate-100 text-slate-800 font-bold px-3 py-1 text-sm border border-slate-300 mb-2">3. VERGİ HESAPLAMASI</h4>
              
              <div className="space-y-1 text-sm">
                 <div className="flex justify-between py-1 border-b border-slate-100">
                    <span className="text-slate-600">Gelir Vergisi Matrahı</span>
                    <span className="font-mono">{formatCurrency(totalTaxableIncome)}</span>
                 </div>
                 <div className="flex justify-between py-1 border-b border-slate-100">
                    <span className="text-slate-600">Hesaplanan Gelir Vergisi</span>
                    <span className="font-mono font-medium">{formatCurrency(calculatedTax)}</span>
                 </div>
                 <div className="flex justify-between py-1 border-b border-slate-100 items-center">
                    <span className="text-slate-600 flex items-center gap-1">
                      Mahsup Edilecek Yabancı Vergiler
                      {deductibleForeignTax > 0 && <span className="text-[10px] text-blue-600 bg-blue-50 px-1 rounded">(Kanıtlayıcı Belge Gerekir)</span>}
                    </span>
                    <span className="font-mono text-green-700">-{formatCurrency(deductibleForeignTax)}</span>
                 </div>
                 <div className="flex justify-between py-1 border-b border-slate-100">
                    <span className="text-slate-600">Ödenecek Gelir Vergisi</span>
                    <span className="font-mono font-bold text-slate-900">{formatCurrency(finalTaxPayable)}</span>
                 </div>
                 <div className="flex justify-between py-1 border-b border-slate-100 text-slate-500 italic">
                    <span>(+) Damga Vergisi (Tahmini 2025)</span>
                    <span className="font-mono">{formatCurrency(stampDuty)}</span>
                 </div>
                 
                 <div className="flex justify-between py-3 mt-2 bg-slate-800 text-white rounded px-3">
                    <span className="font-bold">TOPLAM ÖDENECEK (Vergi + Damga)</span>
                    <span className="font-mono font-bold text-lg">{formatCurrency(finalTaxPayable + stampDuty)}</span>
                 </div>
              </div>
            </div>

            {/* Footer Disclaimer */}
            <div className="text-[10px] text-slate-400 text-center mt-8 pt-4 border-t border-slate-200">
              <p className="flex items-center justify-center gap-1">
                <AlertCircle size={12} />
                <strong>YASAL UYARI:</strong> Bu belge resmi beyanname yerine geçmez. VergiM uygulaması tarafından, kullanıcının girdiği verilere dayalı olarak 
                Hazır Beyan Sistemi'ne (hazirbeyan.gib.gov.tr) veri girişi yapılmasına yardımcı olmak amacıyla oluşturulmuştur.
                Kesin tahakkuk fişi, vergi dairesi sisteminden onaylandıktan sonra oluşacaktır.
              </p>
            </div>

          </div>

          {/* Detailed Calculation Logic (Explainer) */}
          <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden print:break-before-page">
            <div className="bg-slate-50 px-6 py-4 border-b border-slate-200 flex items-center gap-2">
               <Layers size={20} className="text-blue-600" />
               <h3 className="font-bold text-slate-800">Vergi Tarifesi Hesaplama Detayı (Mantık)</h3>
            </div>
            
            <div className="p-6">
              <p className="text-sm text-slate-600 mb-4">
                Toplam <strong>{formatCurrency(totalTaxableIncome)}</strong> matrahınızın artan oranlı gelir vergisi dilimlerine dağılımı aşağıdaki gibidir:
              </p>
              
              <div className="space-y-1">
                {taxBreakdown.map((item, idx) => (
                  <div key={idx} className="flex flex-col sm:flex-row sm:items-center justify-between p-3 rounded bg-slate-50 border border-slate-100 gap-2">
                    <div className="flex items-center gap-3">
                      <span className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold text-white shadow-sm ${
                        item.rate === 0.15 ? 'bg-green-500' : 
                        item.rate === 0.20 ? 'bg-blue-500' : 
                        item.rate === 0.27 ? 'bg-orange-400' : 
                        item.rate === 0.35 ? 'bg-orange-600' : 'bg-red-600'
                      }`}>
                        %{item.rate * 100}
                      </span>
                      <div className="flex flex-col">
                        <span className="text-xs text-slate-500 font-medium">{item.rangeLabel} Dilimi</span>
                        <span className="text-sm font-bold text-slate-800">{formatCurrency(item.base)} (Matrah Payı)</span>
                      </div>
                    </div>
                    
                    <div className="flex items-center gap-2 sm:justify-end border-t sm:border-t-0 border-slate-200 pt-2 sm:pt-0 mt-1 sm:mt-0">
                       <span className="text-xs text-slate-400 hidden sm:inline">x %{item.rate * 100} =</span>
                       <span className="text-sm font-bold text-slate-900">{formatCurrency(item.tax)} Vergi</span>
                    </div>
                  </div>
                ))}

                <div className="flex justify-between items-center p-3 mt-2 bg-blue-50 border border-blue-100 rounded">
                   <div className="flex items-center gap-2 text-blue-800 font-bold">
                     <Sigma size={18} />
                     <span>Toplam Hesaplanan Vergi</span>
                   </div>
                   <span className="text-lg font-bold text-blue-900">{formatCurrency(calculatedTax)}</span>
                </div>
              </div>

              <div className="mt-4 p-3 bg-yellow-50 rounded border border-yellow-100 text-xs text-yellow-800">
                <p>
                  <strong>Not:</strong> Bu hesaplama, yukarıdaki "3. Vergi Hesaplaması" bölümündeki "Hesaplanan Gelir Vergisi" satırının matematiksel ispatıdır.
                  Mahsup edilecek yabancı vergiler (stopaj), bu toplam tutardan düşülür.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};